### ISSUE TITLE
Unable to run the application

### ISSUE THREAD

**Issue by BaggioGiacomo** [xjamundx/exchange-rate#3]
Hi all!
I'm watching a little tutorial on [EggHead.io](https://egghead.io/lessons/react-introducing-redux-with-react-hooks), I've cloned the repo and run `yarn` to install all the packages.
When I run `yarn start`, I get this error:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/58849430/167421538-2be915b8-7f19-4bb0-a70a-8f14cff3add6.png">

## Note
I've tried with npm too, it has also given me errors

How can I fix that?

**Comment by fivetwelve** [comment]
I think there may be a conflict or issue with the dependency and node 18.x. I suggest switching to 16.15.0. Seems to run fine under that version. I endorse using something like `nvm` so that you can use different versions of node as you need them.

Update: v16.15.1 was released recently and the OP's error shows up with that version as well.

**Comment by xjamundx** [comment]
I think you're right @fivetwelve this was developed on an older version of node. I'll take a look at this with the latest and at least update the readme!

**Comment by BaggioGiacomo** [comment]
Yes, you're right @fivetwelve !
Switching to node `16.15.0` fixes this error.
